Update ci-check-new-releases.yml

diff --git a/.github/workflows/ci-check-new-releases.yml b/.github/workflows/ci-check-new-releases.yml
--- a/.github/workflows/ci-check-new-releases.yml
+++ b/.github/workflows/ci-check-new-releases.yml
@@ -27,6 +27,8 @@ jobs:
       bypass_update_check: ${{ inputs.bypass_update_check }}
       bypass_git_commit: ${{ inputs.bypass_git_commit }}
       gnu_mirror_url: ${{ inputs.gnu_mirror_url }}
+      github_repository: ${{ github.repository }}
+      github_workspace: ${{ github.workspace }}
 
     steps:
       - uses: actions/checkout@v4
@@ -40,9 +42,9 @@ jobs:
       - name: boot strap
         id: boot_strap_release
         run: |
-          if curl -sLIf "https://github.com/${{ github.repository }}/releases/latest/download/versions.json" &> /dev/null; then
-              until curl -sLf "https://github.com/${{ github.repository }}/releases/latest/download/versions.json" > remote_versions.json; do
-                echo "waiting for URL."
+          if curl -sLIf "https://github.com/${github_repository}/releases/latest/download/versions.json" &> /dev/null; then
+              until curl -sLf "https://github.com/${github_repository}/releases/latest/download/versions.json" > remote_versions.json; do
+                printf '%s\n' "waiting for URL."
                 sleep 2
               done
           else
@@ -53,10 +55,11 @@ jobs:
           if curl -sLIo /dev/null --fail "http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD"; then
               config_sub="$(git ls-remote "https://git.savannah.gnu.org/git/config.git" | head -n1 | awk '{ print substr($1,1,8) }')"
               printf '%s\n' "savannah.gnu.org is reachable, using git to get config.sub commit hash of remote version"
-              curl -sL "http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD" -o config.sub
+              mkdir -p ${github_workspace}/sources
+              curl -sL "http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD" -o sources/config.sub
           else
               config_sub="$(jq -r .CONFIG_SUB_REV versions.json)"
-              printf '%s\n' "savannah.gnu.org is unreachable (again), using jq to get config.sub commit hash of current version"
+              printf '%s\n' "savannah.gnu.org is unreachable (again), using jq to get sources/config.sub commit hash of current version"
           fi
 
           # current version is determined by getting the versions.json from the latest release
@@ -77,7 +80,7 @@ jobs:
           # Verify the array entries and exit on failure
           for key in "${!remote_versions[@]}"; do
             if [[ -z "${remote_versions[$key]}" ]]; then
-              echo "Error: ${key} is empty"
+              printf '%s\n' "Error: ${key} is empty"
               exit 1
             fi
           done
@@ -86,7 +89,7 @@ jobs:
           remote_urls_dl[CONFIG_SUB_REV]="https://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=${remote_versions[CONFIG_SUB_REV]}"
           remote_urls_dl[GCC_VER]="${gnu_mirror_url}/gcc/gcc-${remote_versions[GCC_VER]}/gcc-${remote_versions[GCC_VER]}.tar.xz"
           remote_urls_dl[BINUTILS_VER]="${gnu_mirror_url}/binutils/binutils-${remote_versions[BINUTILS_VER]}.tar.xz"
-          remote_urls_dl[MUSL_VER]=""
+          remote_urls_dl[MUSL_VER]="https://git.musl-libc.org/cgit/musl/snapshot/musl-${remote_versions[MUSL_VER]}.tar.gz"
           remote_urls_dl[GMP_VER]="${gnu_mirror_url}/gmp/gmp-${remote_versions[GMP_VER]}.tar.xz"
           remote_urls_dl[MPC_VER]="${gnu_mirror_url}/mpc/mpc-${remote_versions[MPC_VER]}.tar.gz"
           remote_urls_dl[MPFR_VER]="${gnu_mirror_url}/mpfr/mpfr-${remote_versions[MPFR_VER]}.tar.xz"
@@ -94,72 +97,62 @@ jobs:
           remote_urls_dl[ISL_VER]="https://libisl.sourceforge.io/isl-${remote_versions[ISL_VER]}.tar.xz"
 
           ver() {
-            local test_array
-            read -ra test_array < <(printf "%s" "${@//./ }")
-            printf "%d%03d%03d%03d" "${test_array[@]}"
+              local input="$1"
+              if [[ "$input" =~ ^[0-9]+(\.[0-9]+)*$ ]]; then
+                  local test_array
+                  read -ra test_array < <(printf "%s" "${input//./ }")
+                  printf "%d%03d%03d%03d" "${test_array[@]}"
+              else
+                  printf "%s" "$input"
+              fi
           }
 
           for iray in "${!current_versions[@]}"; do
-            if [[ ! "$iray" =~ ^(CONFIG_SUB_REV|MUSL_VER)$ ]]; then
-              if [[ "$(ver "${current_versions[$iray]}")" -lt "$(ver "${remote_versions[$iray]}")" ]]; then
-                printf "%-14s current:%-15s remote:%-15s %s\n" "$iray" "${current_versions[$iray]}" "${remote_versions[$iray]}" "< New version available - workflow will be triggered"
+            if [[ "$(ver "${current_versions[$iray]}")" != "$(ver "${remote_versions[$iray]}")" ]]; then
+              printf "%-14s current:%-15s remote:%-15s %s\n" "$iray" "${current_versions[$iray]}" "${remote_versions[$iray]}" "< New version available - workflow will be triggered"
 
+              if [[ "$iray" == "CONFIG_SUB_REV" ]]; then
+                if [[ -z "${use_local_config_sub}" ]]; then
+                  printf '%s' "$(curl -sL "${remote_urls_dl[$iray]}" | sha1sum | sed 's/-/config.sub/')" > "hashes/config.sub.${remote_versions[CONFIG_SUB_REV]}.sha1"
+                fi
+              else
                 # get updated shasum of $iray
                 curl -sL "${remote_urls_dl[$iray]}" -o "${remote_urls_dl[$iray]##*/}"
                 sha1sum "${remote_urls_dl[$iray]##*/}" > "hashes/${remote_urls_dl[$iray]##*/}.sha1"
                 rm -f "${remote_urls_dl[$iray]##*/}"
-
-                # Extract package name more robustly
-                patch_dir_prefix="${iray%_VER}"
-                patch_dir_prefix="${patch_dir_prefix,,}" # Convert to lowercase
-
-                current_patch_dir="patches/${patch_dir_prefix}-${current_versions[$iray]}"
-                new_patch_dir="patches/${patch_dir_prefix}-${remote_versions[$iray]}"
-
-                if [[ -d "${current_patch_dir}" ]]; then
-                    printf '\n%s\n\n' "${current_patch_dir} exists"
-                    printf '%s\n\n' "Does the ${patch_dir_prefix}-${current_versions[$iray]} directory has any patches?" >> $GITHUB_STEP_SUMMARY
-                    if (
-                        shopt -s nullglob dotglob
-                        f=("${current_patch_dir}"/*.diff)
-                        ((${#f[@]}))
-                    ); then
-                        printf '%s\n\n' "It does ... copying them to ${new_patch_dir}" >> $GITHUB_STEP_SUMMARY
-                        # Create directory and copy patches
-                        mkdir -p "${new_patch_dir}"
-                        cp -rf "${current_patch_dir}"/* "${new_patch_dir}/"
-                    else
-                        printf '\n%s\n\n' '${patch_dir_prefix}-${current_versions[$iray]} directory is empty' >> $GITHUB_STEP_SUMMARY
-                    fi
-                else
-                    printf '\n%s\n\n' "${current_patch_dir} does not exist" >> $GITHUB_STEP_SUMMARY
-                    printf '%s\n\n' "no patches to copy over to new version" >> $GITHUB_STEP_SUMMARY
-                fi
-
-                printf '%s\n' "build_new_release=true" >> $GITHUB_OUTPUT
-                build_new_release=true
-              else
-                printf "%-14s current:%-15s remote:%-15s\n" "$iray" "${current_versions[$iray]}" "${remote_versions[$iray]}"
               fi
-            fi
 
-            if [[ "$iray" =~ ^(CONFIG_SUB_REV|MUSL_VER)$ ]]; then
-              if [[ "${current_versions[$iray]}" != "${remote_versions[$iray]}" ]]; then
-                printf "%-14s current:%-15s remote:%-15s %s\n" "$iray" "${current_versions[$iray]}" "${remote_versions[$iray]}" "< New version available - workflow will be triggered"
+              # Extract package name more robustly
+              patch_dir_prefix="${iray%_VER}"
+              patch_dir_prefix="${patch_dir_prefix,,}" # Convert to lowercase
 
-                if [[ "$iray" != "MUSL_VER" ]]; then
-                  if [[ -z "${use_local_config_sub}" ]]; then
-                      printf '%s' "$(curl -sL "${remote_urls_dl[$iray]}" | sha1sum | sed 's/-/config.sub/')" > "hashes/config.sub.${remote_versions[CONFIG_SUB_REV]}.sha1"
-                  fi
+              current_patch_dir="patches/${patch_dir_prefix}-${current_versions[$iray]}"
+              new_patch_dir="patches/${patch_dir_prefix}-${remote_versions[$iray]}"
+
+              ###### copy patches ############################################################
+              if [[ -d "${current_patch_dir}" ]]; then
+                printf '\n%s\n\n' "${current_patch_dir} exists"
+                printf '%s\n\n' "Does the ${patch_dir_prefix}-${current_versions[$iray]} directory has any patches?" >> $GITHUB_STEP_SUMMARY
+                if (
+                  shopt -s nullglob dotglob
+                  f=("${current_patch_dir}"/*.diff)
+                  ((${#f[@]}))
+                ); then
+                  printf '%s\n\n' "It does ... copying them to ${new_patch_dir}" >> $GITHUB_STEP_SUMMARY
+                  # Create directory and copy patches
+                  mkdir -p "${new_patch_dir}"
+                  cp -rf "${current_patch_dir}"/* "${new_patch_dir}/"
+                else
+                  printf '\n%s\n\n' '${patch_dir_prefix}-${current_versions[$iray]} directory is empty' >> $GITHUB_STEP_SUMMARY
                 fi
-
-                printf '%s\n' "build_new_release=true" >> $GITHUB_OUTPUT
-                build_new_release=true
               else
-                printf "%-14s current:%-15s remote:%-15s\n" "$iray" "${current_versions[$iray]}" "${remote_versions[$iray]}"
+                printf '\n%s\n\n' "${current_patch_dir} does not exist" >> $GITHUB_STEP_SUMMARY
+                printf '%s\n\n' "no patches to copy over to new version" >> $GITHUB_STEP_SUMMARY
               fi
             fi
           done
+
+          ###### copy patches ############################################################
 
           printf '%b\n' "# build_new_release?" >> $GITHUB_STEP_SUMMARY
           printf '\n%s\n\n' "build_new_release=${build_new_release}" >> $GITHUB_STEP_SUMMARY
@@ -179,7 +172,9 @@ jobs:
           VERSIONS_JSON
 
           printf '\n%s\n\n' "# existing versions.mak" >> $GITHUB_STEP_SUMMARY
+          printf '\n%b\n' '\`\`\`make' >> $GITHUB_STEP_SUMMARY
           cat versions.mak >> $GITHUB_STEP_SUMMARY
+          printf '\n%b\n' '\`\`\`' >> $GITHUB_STEP_SUMMARY
 
           cat > "versions.mak" <<- VERSIONS_MAK
           CONFIG_SUB_REV = ${remote_versions[CONFIG_SUB_REV]}
@@ -194,27 +189,27 @@ jobs:
           VERSIONS_MAK
 
           printf '\n%s\n\n' "# updated versions.mak" >> $GITHUB_STEP_SUMMARY
+          printf '\n%b\n' '\`\`\`make' >> $GITHUB_STEP_SUMMARY
           cat versions.mak >> $GITHUB_STEP_SUMMARY
+          printf '\n%b\n' '\`\`\`' >> $GITHUB_STEP_SUMMARY
 
           printf '%b\n' "# Remote versions outputs summary" >> $GITHUB_STEP_SUMMARY
-          printf '%b\n' "CONFIG_SUB_REV: ${remote_versions[CONFIG_SUB_REV]}" >> $GITHUB_STEP_SUMMARY
-          printf '%b\n' "GCC_VER: ${remote_versions[GCC_VER]}" >> $GITHUB_STEP_SUMMARY
-          printf '%b\n' "BINUTILS_VER: ${remote_versions[BINUTILS_VER]}" >> $GITHUB_STEP_SUMMARY
-          printf '%b\n' "MUSL_VER: ${remote_versions[MUSL_VER]}" >> $GITHUB_STEP_SUMMARY
-          printf '%b\n' "GMP_VER: ${remote_versions[GMP_VER]}" >> $GITHUB_STEP_SUMMARY
-          printf '%b\n' "MPC_VER: ${remote_versions[MPC_VER]}" >> $GITHUB_STEP_SUMMARY
-          printf '%b\n' "MPFR_VER: ${remote_versions[MPFR_VER]}" >> $GITHUB_STEP_SUMMARY
-          printf '%b\n' "LINUX_VER: ${remote_versions[LINUX_VER]}" >> $GITHUB_STEP_SUMMARY
-          printf '%b\n' "ISL_VER: ${remote_versions[ISL_VER]}" >> $GITHUB_STEP_SUMMARY
+          printf '\n%b\n' '\`\`\`make' >> $GITHUB_STEP_SUMMARY
+
+          for iray in "${!current_versions[@]}"; do
+            printf '%b\n' "$iray: ${remote_versions[$iray]}" >> $GITHUB_STEP_SUMMARY
+          done
+
+          printf '\n%b\n' '\`\`\`' >> $GITHUB_STEP_SUMMARY
 
           if [[ ${bypass_update_check} == 'true' ]] ; then
             printf '%s\n' "build_new_release=true" >> $GITHUB_OUTPUT
           fi
 
           if [[ ${bypass_git_commit} == 'true' ]] ; then
-              printf '\n%s\n\n' "# Git changes will be: skipped" >> $GITHUB_STEP_SUMMARY
+            printf '\n%s\n\n' "# Git changes will be: skipped" >> $GITHUB_STEP_SUMMARY
           else
-              printf '\n%s\n\n' "# Git changes will be: committed" >> $GITHUB_STEP_SUMMARY
+            printf '\n%s\n\n' "# Git changes will be: committed" >> $GITHUB_STEP_SUMMARY
           fi
 
       # This step only runs of if steps.boot_strap_release.outputs.build_new_release == 'true'
@@ -227,9 +222,9 @@ jobs:
         run: |
           # Only run git commands if there are actual changes
           if [[ -f "versions.json" ]] && [[ -f "versions.mak" ]] && [[ -d "hashes" ]] && [[ -d "patches" ]] && [[ -f "config.sub" ]]; then
-            git add versions.json versions.mak hashes/*.sha1 patches/* config.sub || true
+            git add versions.json versions.mak hashes/*.sha1 patches/* sources/config.sub || true
             git status --porcelain | grep -q . && {
             git -c user.name='github-actions[bot]' -c user.email='github-actions[bot]@users.noreply.github.com' commit -m "Automated commit by GitHub Actions"
             git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
-            } || echo "No changes detected"
+            } || printf '%s\n' "No changes detected"
           fi
